NAVIGATION_REFERENCE_JSON = {
    "navigationContext": {
        "type": "hybrid",
        "primaryNavigation": {
            "type": "sidebar",
            "layout": "vertical",
            "position": "left",
            "width": "240px",
            "collapsible": True,
            "defaultCollapsed": False,
            "persistState": True,
        },
        "secondaryNavigation": {
            "type": "tabs",
            "position": "top",
            "style": "underlined",
        },
        "mobileNavigation": {
            "type": "bottomTab",
            "hideOnScroll": False,
            "showLabels": True,
        },
        "navigationItems": [
            {
                "id": "dashboard",
                "label": "Dashboard",
                "icon": "TrendingUp",
                "path": "/dashboard",
                "active": True,
                "badge": None,
                "description": "Overview of your investments and portfolio performance",
                "accessLevel": "all",
                "category": "main",
            },
            {
                "id": "portfolio",
                "label": "Portfolio",
                "icon": "PieChart",
                "path": "/portfolio",
                "active": False,
                "badge": None,
                "description": "Manage and track your investment portfolio",
                "accessLevel": "all",
                "category": "main",
                "subItems": [
                    {
                        "id": "holdings",
                        "label": "Holdings",
                        "path": "/portfolio/holdings",
                        "description": "View all your current investments",
                    },
                    {
                        "id": "performance",
                        "label": "Performance",
                        "path": "/portfolio/performance",
                        "description": "Analyze portfolio performance and returns",
                    },
                    {
                        "id": "allocation",
                        "label": "Asset Allocation",
                        "path": "/portfolio/allocation",
                        "description": "Review and adjust your asset allocation",
                    },
                ],
            },
            {
                "id": "markets",
                "label": "Markets",
                "icon": "BarChart3",
                "path": "/markets",
                "active": False,
                "badge": "live",
                "description": "Real-time market data and analysis",
                "accessLevel": "all",
                "category": "main",
                "subItems": [
                    {
                        "id": "watchlist",
                        "label": "Watchlist",
                        "path": "/markets/watchlist",
                        "description": "Track your favorite stocks and securities",
                    },
                    {
                        "id": "screener",
                        "label": "Stock Screener",
                        "path": "/markets/screener",
                        "description": "Find investment opportunities based on criteria",
                    },
                    {
                        "id": "news",
                        "label": "Market News",
                        "path": "/markets/news",
                        "description": "Latest financial news and market updates",
                    },
                ],
            },
            {
                "id": "trading",
                "label": "Trading",
                "icon": "ArrowRightLeft",
                "path": "/trading",
                "active": False,
                "badge": None,
                "description": "Execute trades and manage orders",
                "accessLevel": "verified",
                "category": "main",
                "subItems": [
                    {
                        "id": "buy-sell",
                        "label": "Buy/Sell",
                        "path": "/trading/order",
                        "description": "Place buy and sell orders",
                    },
                    {
                        "id": "orders",
                        "label": "Order History",
                        "path": "/trading/orders",
                        "description": "View and manage your trading orders",
                    },
                    {
                        "id": "tax-documents",
                        "label": "Tax Documents",
                        "path": "/trading/tax-documents",
                        "description": "Download tax forms and documents",
                    },
                ],
            },
            {
                "id": "research",
                "label": "Research",
                "icon": "Search",
                "path": "/research",
                "active": False,
                "badge": None,
                "description": "Investment research and analysis tools",
                "accessLevel": "all",
                "category": "main",
                "subItems": [
                    {
                        "id": "analyst-reports",
                        "label": "Analyst Reports",
                        "path": "/research/reports",
                        "description": "Professional investment research and recommendations",
                    },
                    {
                        "id": "company-profiles",
                        "label": "Company Profiles",
                        "path": "/research/companies",
                        "description": "Detailed company information and financials",
                    },
                    {
                        "id": "economic-data",
                        "label": "Economic Data",
                        "path": "/research/economic",
                        "description": "Economic indicators and market trends",
                    },
                ],
            },
            {
                "id": "goals",
                "label": "Goals",
                "icon": "Target",
                "path": "/goals",
                "active": False,
                "badge": "3",
                "description": "Set and track your financial goals",
                "accessLevel": "all",
                "category": "planning",
            },
            {
                "id": "education",
                "label": "Education",
                "icon": "BookOpen",
                "path": "/education",
                "active": False,
                "badge": None,
                "description": "Learn about investing and financial planning",
                "accessLevel": "all",
                "category": "support",
                "subItems": [
                    {
                        "id": "courses",
                        "label": "Courses",
                        "path": "/education/courses",
                        "description": "Structured learning courses",
                    },
                    {
                        "id": "articles",
                        "label": "Articles",
                        "path": "/education/articles",
                        "description": "Educational articles and guides",
                    },
                    {
                        "id": "webinars",
                        "label": "Webinars",
                        "path": "/education/webinars",
                        "description": "Live and recorded educational sessions",
                    },
                ],
            },
            {
                "id": "settings",
                "label": "Settings",
                "icon": "Settings",
                "path": "/settings",
                "active": False,
                "badge": None,
                "description": "Account and application settings",
                "accessLevel": "all",
                "category": "account",
            },
        ],
        "userMenu": {
            "trigger": "avatar",
            "avatar": "/api/placeholder/40/40",
            "name": "John Investor",
            "email": "john@example.com",
            "accountType": "Premium",
            "accountValue": "$125,450.67",
            "menuItems": [
                {
                    "label": "Account Overview",
                    "icon": "User",
                    "action": "navigate",
                    "path": "/account/overview",
                    "description": "View account details and verification status",
                },
                {
                    "label": "Security Settings",
                    "icon": "Shield",
                    "action": "navigate",
                    "path": "/account/security",
                    "description": "Manage passwords and two-factor authentication",
                },
                {
                    "label": "Notification Preferences",
                    "icon": "Bell",
                    "action": "navigate",
                    "path": "/account/notifications",
                    "description": "Customize email and push notifications",
                },
                {
                    "label": "Help & Support",
                    "icon": "HelpCircle",
                    "action": "navigate",
                    "path": "/support",
                    "description": "Get help and contact support",
                },
                {"type": "divider"},
                {
                    "label": "Sign Out",
                    "icon": "LogOut",
                    "action": "logout",
                    "path": None,
                    "description": "Securely sign out of your account",
                },
            ],
        },
        "behavior": {
            "active_state_indication": True,
            "collapse_on_mobile": True,
            "persist_state": True,
            "keyboard_shortcuts": {
                "toggle_sidebar": "cmd+b",
                "search": "cmd+k",
            },
        },
        "search": {
            "enabled": True,
            "placeholder": "Search pages...",
            "shortcut": "cmd+k",
            "scope": "global",
        },
        "breadcrumbs": {
            "enabled": True,
            "separator": "/",
            "showHome": True,
            "maxItems": 4,
            "collapseStrategy": "middle",
        },
        "quickActions": {
            "enabled": True,
            "position": "floating",
            "trigger": "Plus",
            "actions": [
                {
                    "label": "Buy Stock",
                    "icon": "TrendingUp",
                    "action": "navigate",
                    "path": "/trading/buy",
                    "hotkey": "Cmd+B",
                },
                {
                    "label": "Add to Watchlist",
                    "icon": "Eye",
                    "action": "modal",
                    "component": "AddToWatchlistModal",
                    "hotkey": "Cmd+W",
                },
                {
                    "label": "Transfer Funds",
                    "icon": "ArrowRightLeft",
                    "action": "navigate",
                    "path": "/account/transfer",
                    "hotkey": "Cmd+T",
                },
            ],
        },
    }
}
