SCREEN_REFERENCE_JSON = {
    "id": "dashboard",
    "name": "Investment Dashboard",
    "route": "/dashboard",
    "layout": "main",
    "description": "Comprehensive overview of user's investment portfolio and market insights",
    "pageTitle": "Dashboard - InvestFlow Pro",
    "metaDescription": "Track your investment portfolio performance, market trends, and get personalized insights",
    "accessLevel": "authenticated",
    "cacheStrategy": "stale-while-revalidate",
    "updateFrequency": "real-time",
    "components": [
        {
            "id": "page-header",
            "type": "pageHeader",
            "order": 1,
            "props": {
                "title": "Investment Dashboard",
                "subtitle": "Welcome back, John. Here's your portfolio overview.",
                "showDateTime": True,
                "showMarketStatus": True,
                "actions": [
                    {
                        "label": "Quick Trade",
                        "variant": "primary",
                        "icon": "Zap",
                        "action": "navigate",
                        "path": "/trading/quick",
                    },
                    {
                        "label": "Add Funds",
                        "variant": "secondary",
                        "icon": "Plus",
                        "action": "modal",
                        "component": "AddFundsModal",
                    },
                ],
            },
            "responsive": {
                "mobile": {"hideSubtitle": True, "stackActions": True}
            },
        },
        {
            "id": "portfolio-summary",
            "type": "portfolioSummaryCard",
            "order": 2,
            "props": {
                "showTotalValue": True,
                "showDayChange": True,
                "showTotalReturn": True,
                "showCashBalance": True,
                "animateNumbers": True,
                "refreshInterval": 30000,
            },
            "layout": {"span": "full", "minHeight": "200px"},
        },
        {
            "id": "market-overview",
            "type": "marketOverviewWidget",
            "order": 3,
            "props": {
                "indices": ["SPY", "QQQ", "IWM", "DIA"],
                "showChart": True,
                "timeframe": "1D",
                "refreshInterval": 60000,
            },
            "layout": {"span": "2/3", "minHeight": "300px"},
        },
        {
            "id": "quick-stats",
            "type": "statsGrid",
            "order": 4,
            "props": {
                "columns": 1,
                "spacing": "compact",
                "stats": [
                    {
                        "id": "buying-power",
                        "label": "Buying Power",
                        "value": "$12,450.67",
                        "icon": "DollarSign",
                        "description": "Available cash for trading",
                    },
                    {
                        "id": "positions",
                        "label": "Open Positions",
                        "value": "23",
                        "icon": "TrendingUp",
                        "description": "Number of active holdings",
                    },
                    {
                        "id": "watchlist-movers",
                        "label": "Watchlist Movers",
                        "value": "5",
                        "change": "+2",
                        "changeType": "positive",
                        "icon": "Eye",
                        "description": "Significant price movements",
                    },
                ],
            },
            "layout": {"span": "1/3", "minHeight": "300px"},
        },
        {
            "id": "portfolio-allocation",
            "type": "portfolioAllocationChart",
            "order": 5,
            "props": {
                "chartType": "doughnut",
                "showLegend": True,
                "showPercentages": True,
                "showValues": True,
                "interactive": True,
                "title": "Asset Allocation",
            },
            "layout": {"span": "1/2", "minHeight": "400px"},
        },
        {
            "id": "performance-chart",
            "type": "performanceChart",
            "order": 6,
            "props": {
                "timeframes": ["1D", "1W", "1M", "3M", "1Y", "MAX"],
                "defaultTimeframe": "1M",
                "showBenchmark": True,
                "benchmarkSymbol": "SPY",
                "chartType": "line",
                "showVolume": False,
                "interactive": True,
                "title": "Portfolio Performance",
            },
            "layout": {"span": "1/2", "minHeight": "400px"},
        },
        {
            "id": "top-holdings",
            "type": "holdingsTable",
            "order": 7,
            "props": {
                "title": "Top Holdings",
                "limit": 10,
                "showChart": True,
                "sortBy": "value",
                "sortOrder": "desc",
                "columns": [
                    "symbol",
                    "name",
                    "shares",
                    "price",
                    "value",
                    "dayChange",
                    "totalReturn",
                    "allocation",
                ],
                "clickable": True,
                "showPagination": False,
            },
            "layout": {"span": "full", "minHeight": "400px"},
        },
        {
            "id": "market-news",
            "type": "newsWidget",
            "order": 8,
            "props": {
                "title": "Market News",
                "limit": 5,
                "sources": ["reuters", "bloomberg", "marketwatch"],
                "categories": ["markets", "stocks", "economy"],
                "showImages": True,
                "showTimestamp": True,
                "refreshInterval": 300000,
            },
            "layout": {"span": "1/2", "minHeight": "400px"},
        },
        {
            "id": "watchlist-preview",
            "type": "watchlistWidget",
            "order": 9,
            "props": {
                "title": "Watchlist",
                "limit": 8,
                "showChart": True,
                "showAlerts": True,
                "columns": ["symbol", "price", "change", "volume"],
                "refreshInterval": 5000,
            },
            "layout": {"span": "1/2", "minHeight": "400px"},
        },
    ],
    "data": {
        "portfolioSummary": {
            "totalValue": 125450.67,
            "dayChange": {"amount": 1234.56, "percentage": 0.99},
            "totalReturn": {"amount": 25450.67, "percentage": 25.45},
            "cashBalance": 12450.67,
            "buyingPower": 12450.67,
            "marginUsed": 0,
            "lastUpdated": "2024-06-03T14:30:00Z",
        },
        "marketIndices": [
            {
                "symbol": "SPY",
                "name": "SPDR S&P 500 ETF",
                "price": 521.43,
                "change": 2.34,
                "changePercent": 0.45,
                "volume": 45678901,
            },
            {
                "symbol": "QQQ",
                "name": "Invesco QQQ Trust",
                "price": 387.65,
                "change": -1.23,
                "changePercent": -0.32,
                "volume": 23456789,
            },
            {
                "symbol": "IWM",
                "name": "iShares Russell 2000 ETF",
                "price": 198.76,
                "change": 0.87,
                "changePercent": 0.44,
                "volume": 12345678,
            },
            {
                "symbol": "DIA",
                "name": "SPDR Dow Jones Industrial Average ETF",
                "price": 396.54,
                "change": 1.65,
                "changePercent": 0.42,
                "volume": 8765432,
            },
        ],
        "portfolioAllocation": [
            {
                "category": "US Stocks",
                "value": 75270.40,
                "percentage": 60.0,
                "color": "#1e40af",
            },
            {
                "category": "International Stocks",
                "value": 25090.13,
                "percentage": 20.0,
                "color": "#059669",
            },
            {
                "category": "Bonds",
                "value": 12545.07,
                "percentage": 10.0,
                "color": "#dc2626",
            },
            {
                "category": "REITs",
                "value": 6272.53,
                "percentage": 5.0,
                "color": "#d97706",
            },
            {
                "category": "Cash",
                "value": 6272.53,
                "percentage": 5.0,
                "color": "#6b7280",
            },
        ],
        "topHoldings": [
            {
                "symbol": "AAPL",
                "name": "Apple Inc.",
                "shares": 100,
                "price": 189.25,
                "value": 18925.00,
                "dayChange": {"amount": 125.00, "percentage": 0.66},
                "totalReturn": {"amount": 2925.00, "percentage": 18.29},
                "allocation": 15.08,
            },
            {
                "symbol": "MSFT",
                "name": "Microsoft Corporation",
                "shares": 50,
                "price": 332.89,
                "value": 16644.50,
                "dayChange": {"amount": 89.50, "percentage": 0.54},
                "totalReturn": {"amount": 1644.50, "percentage": 10.96},
                "allocation": 13.27,
            },
            {
                "symbol": "GOOGL",
                "name": "Alphabet Inc. Class A",
                "shares": 75,
                "price": 168.56,
                "value": 12642.00,
                "dayChange": {"amount": -67.50, "percentage": -0.53},
                "totalReturn": {"amount": 2142.00, "percentage": 20.38},
                "allocation": 10.08,
            },
        ],
        "performanceHistory": [
            {
                "date": "2024-05-01",
                "portfolioValue": 120000.00,
                "benchmarkValue": 100000.00,
            },
            {
                "date": "2024-05-15",
                "portfolioValue": 122500.00,
                "benchmarkValue": 101200.00,
            },
            {
                "date": "2024-06-01",
                "portfolioValue": 124200.00,
                "benchmarkValue": 102100.00,
            },
            {
                "date": "2024-06-03",
                "portfolioValue": 125450.67,
                "benchmarkValue": 102400.00,
            },
        ],
    },
    "seo": {
        "title": "Investment Dashboard - InvestFlow Pro",
        "description": "Track your investment portfolio performance, view market trends, and get personalized investment insights with InvestFlow Pro.",
        "keywords": [
            "investment dashboard",
            "portfolio tracking",
            "stock market",
            "financial planning",
        ],
        "openGraph": {
            "title": "My Investment Dashboard",
            "description": "Professional investment tracking and portfolio management",
            "image": "/images/dashboard-preview.jpg",
        },
    },
    "analytics": {
        "pageView": "dashboard_view",
        "events": [
            "portfolio_value_view",
            "holdings_table_interaction",
            "performance_chart_timeframe_change",
            "quick_trade_button_click",
            "watchlist_symbol_click",
        ],
    },
}
